# Generated by Django 4.0.6 on 2022-08-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_aluno_email_aluno_endereco_completo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escola', models.CharField(max_length=70, verbose_name='escola')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('telefone', models.CharField(max_length=20, verbose_name='telefone')),
                ('endereco', models.CharField(max_length=300, verbose_name='endereco')),
                ('cidade', models.CharField(max_length=100, verbose_name='cidade')),
                ('estado', models.CharField(max_length=100, verbose_name='estado')),
            ],
        ),
    ]
